### ISSUE TITLE
Bug if "collapses-comments": false

### ISSUE THREAD

**Issue by kepon85** [jacobwb/hashover-next#279]
Hello and thank you for this great software

If in my hashover / config / settings.json file the "collapses-comments" option is false I have a bug as soon as I publish a second comment on a page.

In the javascript console I have this:
- XHRPOST http: //chezmoi/hashover/backend/form-actions.php
[HTTP / 1.1 200 OK 212ms]
- TypeError: this.appendComments is not a function

This error occurs when I click on "post", the page stops there but the comment is saved (if I refresh the page I see it)

Note: this problem does not exist if the comment is the first of the page but for all the others it will be the case.

As soon as I pass this parameter to true, everything comes back in order I no longer have an error message in the javascript console.

It is not a problem for me but I will put it back to you if it bothers someone else ...

David

P.S. I intend to contribute by creating a migration script from Wordpress to hashover

**Comment by jacobwb** [comment]
Thank you for pointing this out. It was likely caused by commit 2b87a084f84b073b208b4157500d16a5ba17dbe3, which utilized existing code to append new comments according to the selected sorting order. The cause of the problem was the code for the `appendComments` function was not being loaded when the comment collapsing feature was disabled, which made sense before this commit, but not anymore.

I am closing this issue, please reopen it if it isn't fixed for you.

**Comment by kepon85** [comment]
Yes it's ok !
Thank's !
